/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BroadcastRouteImport } from './routes/broadcast'
import { Route as CardRouteImport } from './routes/card'
import { Route as DamageRouteImport } from './routes/damage'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as GazetteRouteImport } from './routes/gazette'
import { Route as HonorsRouteImport } from './routes/honors'
import { Route as MapRouteImport } from './routes/map'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as WeekRouteImport } from './routes/week'
import { Route as BoutBoutIdRouteImport } from './routes/bout.$boutId'
import { Route as GarageStoreIdRouteImport } from './routes/garage.$storeId'
import { Route as RecapStoreIdRouteImport } from './routes/recap.$storeId'
import { Route as ShopStoreIdRouteImport } from './routes/shop.$storeId'
import { Route as StoresStoreIdRouteImport } from './routes/stores.$storeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastRoute = BroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageRoute = DamageRouteImport.update({
  id: '/damage',
  path: '/damage',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GazetteRoute = GazetteRouteImport.update({
  id: '/gazette',
  path: '/gazette',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorsRoute = HonorsRouteImport.update({
  id: '/honors',
  path: '/honors',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekRoute = WeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutBoutIdRoute = BoutBoutIdRouteImport.update({
  id: '/bout/$boutId',
  path: '/bout/$boutId',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageStoreIdRoute = GarageStoreIdRouteImport.update({
  id: '/garage/$storeId',
  path: '/garage/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapStoreIdRoute = RecapStoreIdRouteImport.update({
  id: '/recap/$storeId',
  path: '/recap/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopStoreIdRoute = ShopStoreIdRouteImport.update({
  id: '/shop/$storeId',
  path: '/shop/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/broadcast': typeof BroadcastRoute
  '/card': typeof CardRoute
  '/damage': typeof DamageRoute
  '/desk': typeof DeskRoute
  '/gazette': typeof GazetteRoute
  '/honors': typeof HonorsRoute
  '/map': typeof MapRoute
  '/preview': typeof PreviewRoute
  '/rules': typeof RulesRoute
  '/watch': typeof WatchRoute
  '/week': typeof WeekRoute
  '/bout/$boutId': typeof BoutBoutIdRoute
  '/garage/$storeId': typeof GarageStoreIdRoute
  '/recap/$storeId': typeof RecapStoreIdRoute
  '/shop/$storeId': typeof ShopStoreIdRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/broadcast': typeof BroadcastRoute
  '/card': typeof CardRoute
  '/damage': typeof DamageRoute
  '/desk': typeof DeskRoute
  '/gazette': typeof GazetteRoute
  '/honors': typeof HonorsRoute
  '/map': typeof MapRoute
  '/preview': typeof PreviewRoute
  '/rules': typeof RulesRoute
  '/watch': typeof WatchRoute
  '/week': typeof WeekRoute
  '/bout/$boutId': typeof BoutBoutIdRoute
  '/garage/$storeId': typeof GarageStoreIdRoute
  '/recap/$storeId': typeof RecapStoreIdRoute
  '/shop/$storeId': typeof ShopStoreIdRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/broadcast': typeof BroadcastRoute
  '/card': typeof CardRoute
  '/damage': typeof DamageRoute
  '/desk': typeof DeskRoute
  '/gazette': typeof GazetteRoute
  '/honors': typeof HonorsRoute
  '/map': typeof MapRoute
  '/preview': typeof PreviewRoute
  '/rules': typeof RulesRoute
  '/watch': typeof WatchRoute
  '/week': typeof WeekRoute
  '/bout/$boutId': typeof BoutBoutIdRoute
  '/garage/$storeId': typeof GarageStoreIdRoute
  '/recap/$storeId': typeof RecapStoreIdRoute
  '/shop/$storeId': typeof ShopStoreIdRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/broadcast'
    | '/card'
    | '/damage'
    | '/desk'
    | '/gazette'
    | '/honors'
    | '/map'
    | '/preview'
    | '/rules'
    | '/watch'
    | '/week'
    | '/bout/$boutId'
    | '/garage/$storeId'
    | '/recap/$storeId'
    | '/shop/$storeId'
    | '/stores/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/broadcast'
    | '/card'
    | '/damage'
    | '/desk'
    | '/gazette'
    | '/honors'
    | '/map'
    | '/preview'
    | '/rules'
    | '/watch'
    | '/week'
    | '/bout/$boutId'
    | '/garage/$storeId'
    | '/recap/$storeId'
    | '/shop/$storeId'
    | '/stores/$storeId'
  id:
    | '__root__'
    | '/'
    | '/broadcast'
    | '/card'
    | '/damage'
    | '/desk'
    | '/gazette'
    | '/honors'
    | '/map'
    | '/preview'
    | '/rules'
    | '/watch'
    | '/week'
    | '/bout/$boutId'
    | '/garage/$storeId'
    | '/recap/$storeId'
    | '/shop/$storeId'
    | '/stores/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BroadcastRoute: typeof BroadcastRoute
  CardRoute: typeof CardRoute
  DamageRoute: typeof DamageRoute
  DeskRoute: typeof DeskRoute
  GazetteRoute: typeof GazetteRoute
  HonorsRoute: typeof HonorsRoute
  MapRoute: typeof MapRoute
  PreviewRoute: typeof PreviewRoute
  RulesRoute: typeof RulesRoute
  WatchRoute: typeof WatchRoute
  WeekRoute: typeof WeekRoute
  BoutBoutIdRoute: typeof BoutBoutIdRoute
  GarageStoreIdRoute: typeof GarageStoreIdRoute
  RecapStoreIdRoute: typeof RecapStoreIdRoute
  ShopStoreIdRoute: typeof ShopStoreIdRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage': {
      id: '/damage'
      path: '/damage'
      fullPath: '/damage'
      preLoaderRoute: typeof DamageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gazette': {
      id: '/gazette'
      path: '/gazette'
      fullPath: '/gazette'
      preLoaderRoute: typeof GazetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honors': {
      id: '/honors'
      path: '/honors'
      fullPath: '/honors'
      preLoaderRoute: typeof HonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week': {
      id: '/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof WeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bout/$boutId': {
      id: '/bout/$boutId'
      path: '/bout/$boutId'
      fullPath: '/bout/$boutId'
      preLoaderRoute: typeof BoutBoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/$storeId': {
      id: '/garage/$storeId'
      path: '/garage/$storeId'
      fullPath: '/garage/$storeId'
      preLoaderRoute: typeof GarageStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap/$storeId': {
      id: '/recap/$storeId'
      path: '/recap/$storeId'
      fullPath: '/recap/$storeId'
      preLoaderRoute: typeof RecapStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$storeId': {
      id: '/shop/$storeId'
      path: '/shop/$storeId'
      fullPath: '/shop/$storeId'
      preLoaderRoute: typeof ShopStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BroadcastRoute: BroadcastRoute,
  CardRoute: CardRoute,
  DamageRoute: DamageRoute,
  DeskRoute: DeskRoute,
  GazetteRoute: GazetteRoute,
  HonorsRoute: HonorsRoute,
  MapRoute: MapRoute,
  PreviewRoute: PreviewRoute,
  RulesRoute: RulesRoute,
  WatchRoute: WatchRoute,
  WeekRoute: WeekRoute,
  BoutBoutIdRoute: BoutBoutIdRoute,
  GarageStoreIdRoute: GarageStoreIdRoute,
  RecapStoreIdRoute: RecapStoreIdRoute,
  ShopStoreIdRoute: ShopStoreIdRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
